### ISSUE TITLE
bitfusion server can't reachable

### ISSUE THREAD

**Issue by Goseokbin** [vmware/bitfusion-with-kubernetes-integration#27]
Hi.
I'm try to integrate bitfusion with k8s. 
so I installed bitfusion plugin successfully
but, after create pod(option1 yaml) i got an error.
in front of bitfusion server host ,append - and whitespace 
how to fix?
![무제](https://user-images.githubusercontent.com/37431938/124250258-ab76d580-db5f-11eb-9f22-4a8692b8540a.png)

**Comment by pbarker** [comment]
Also seeing this

**Comment by 4everming** [comment]
Hi, could you provide the Bitfusion Server version and the yaml file that you create the pod by?

**Comment by haozheng95** [comment]
Can you show me the contents of client. Yaml and servers.conf?

**Comment by pbarker** [comment]
Hey @4everming and @haozheng95 

client.yaml
```yaml
version: ""
ssl: true
cacertpath: /etc/bitfusion/tls/ca.crt
keypath: /etc/bitfusion/tls/bitfusion.key
certpath: /etc/bitfusion/tls/bitfusion.crt
dbcertpath: /etc/bitfusion/tls/ca.crt
min-tls-version: ""
timeout: 3s
authconfig:
  enabled: true
  username: ""
  password: ""
  dbusername: ""
  dbpassword: ""
  token: <redacted>
network: {}
dispatcher:
  enabled: true
  rdma:
    rsocket: true
    hops: 2
  srs:
    auto_release_timeout: 10m
  cache_store:
    client_root: /root/.bitfusion/cache
    client_cleanup_threshold_MB: 5120
    server_root: /var/cache/bitfusion
    server_cleanup_threshold_MB: 5120
```

servers.conf
```yaml
servers:
- addresses:
  - 10.202.122.248:5600
```

Bitfusion server version 3.5.0

The yaml file I used for the pod was https://github.com/vmware/bitfusion-with-kubernetes-integration/blob/main/bitfusion_device_plugin/example/pod.yaml
